name: Telegram Proxy Auto Post

on:
  schedule:
    - cron: '0 */3 * * *' # Har 3 ghante baad auto-run hoga
  workflow_dispatch: # Manual test ke liye

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Scraper Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_NAME: ${{ secrets.CHANNEL_NAME }}
        run: python main.py
